# --------------------
# Define arguments.
# --------------------

# ==================== Maa ====================

Scheduler:
  Enable: false
  NextRun: 2020-01-01 04:00:00
  Command: Maa
  SuccessInterval:
    value: 60
    display: hide
  FailureInterval:
    value: 120
    display: hide
  ServerUpdate:
    value: 04:00
    display: hide

Emulator:
  ServerName:
    value: disabled
    display: hide
Error:
  SaveError:
    value: false
    display: hide
  OnePushConfig:
    mode: yaml
    value: 'provider: null'
    display: hide
Optimization:
  WhenTaskQueueEmpty:
    value: stay_there
    display: hide

MaaEmulator:
  Serial:
    value: 127.0.0.1:5555
    valuetype: str
  PackageName:
    value: Official
    option: [Official, Bilibili]
  Server:
    value: CN
    option: [CN, US, JP, KR]
    display: hide
  MaaPath:
    value: D:/Program Files/MAA
    type: textarea
MaaRecord:
  ReportToPenguin: false
  PenguinID: null

MaaFight:
  Stage:
    value: 1-7
    valuetype: str
  Medicine: 0
  Stone: 0
  Times: 0
  Drops:
    value: null
    type: textarea
  DrGrandet: false

MaaRecruit:
  Refresh: true
  SkipRobot: true
  Select3: true
  Select4: true
  Select5: true
  Level3ShortTime: True
  Times: 4
  Expedite: false

MaaInfrast:
  Facility:
    value: Mfg > Trade > Power > Control > Reception > Office > Dorm
    type: textarea
  Drones:
    value: Money
    option: [_NotUse, Money, SyntheticJade, CombatRecord, PureGold, OriginStone, Chip]
  Threshold: 0.3
  Notstationed: true
  Trust: true
  Replenish: false
MaaCustomInfrast:
  Enable: false
  Filename:
    value: null
    type: textarea

MaaMall:
  Shopping: true
  BuyFirst:
    value: 招聘许可 > 龙门币
    type: textarea
  BlackList:
    value: 碳 > 家具
    type: textarea

MaaRoguelike:
  Theme:
    value: Phantom
    option: [Phantom, Mizuki]
  Mode:
    value: 0
    option: [0, 1]
  StartsCount: 9999999
  InvestmentsCount: 9999999
  StopWhenInvestmentFull: false
  Squad:
    value: 指挥分队
    option: [心胜于物分队, 物尽其用分队, 以人为本分队, 指挥分队, 集群分队, 后勤分队, 矛头分队, 突击战术分队, 堡垒战术分队, 远程战术分队, 破坏战术分队, 研究分队, 高规格分队]
  Roles:
    value: 取长补短
    option: [先手必胜, 稳扎稳打, 取长补短, 随心所欲]
  CoreChar: null

# ==================== Tool ====================

MaaCopilot:
  FileName:
    value: null
    type: textarea
  Formation: false


